### PR TITLE
Add Type Option for dbsetmap

### PR DESCRIPTION
**Pull request by IrPgFKS0**
The other pull request got me thinking, "we can do better" so this is my thought to allow setting both the sdictValue and type (within the allowable list) all from cmdline.  I use my phone a lot to manage this and logging into the control panel is just untenable most of the time, this solves that entirely and with less code :).

### CODE REVIEW

**Review by NaruDevnote — APPROVED** [review]
Changes look good, would definitely be better and easier than the manual parsing lol. 👍

**Comment by TheHDCrafter** [comment]
I'll move my ass soon. Sry that i have been ignoring this pr for a bit now. I might even do it after Christmas idk.
Soon:tm: :)

**Comment by IrPgFKS0** [comment]
Thanks all, looks like the “embed” message might need to be reworked too since it doesn’t show the <sdictValue> if this is merged, I didn’t update that.

**Comment by TheHDCrafter** [comment]
I'll check it out soon, give me a few days (sry that i am so slow at looking at pr's)

**Comment by TheHDCrafter** [comment]
Hmmm i looked at the 2 pr's now and yours also looks great, i might even add yours over Devonte's. I'll think about it and add it soon

**Comment by IrPgFKS0** [comment]
Hey HD Crafter, my discord is "@modderan"

**Comment by TheHDCrafter** [comment]
Adding this pr as dbsetmap - basic.gotmpl to the map folder :)
Thank you @IrPgFKS0 for contributing. I will add your name into the credits at the top of the file. 
Also i know this is a little late but happy new year 😁

**Pull request closed without merging**
